spring.datasource.url=jdbc:postgresql://localhost:5432/loja
spring.datasource.username=postgres
spring.datasource.password=adm
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

jwt.secret=${JWT_SECRET:super-extra-chave-jwt-local-2026-com-mais-de-32-caracteres}
jwt.expiration-seconds=3600